### ISSUE TITLE
Informed Citizen Worried about Bias

### ISSUE THREAD

**Issue by sly-yush** [code4policy/2024-b3-Ukraine-media#12]
**As an** informed citizen, **I want** to understand how various media firms portray the war in Ukraine **so I can** have a better understanding of pushed narratives and biases in reporting.

**Comment by abeskrovna** [comment]
Score: 5

**Comment by sly-yush** [comment]
Definition of Done: 

- [x] Users submitted feedback via the feedback form provided indicating they had a better understanding of pushed narratives and biases in reporting after using the website.
