### ISSUE TITLE
Political Campaign Strategist

### ISSUE THREAD

**Issue by abeskrovna** [code4policy/2024-b3-Ukraine-media#20]
As a campaign strategist for a political candidate supporting aid for Ukraine, I want to access a visualization of the mentions of Ukraine in state-level and national media, so that I can tailor my social media content better.

**Comment by abeskrovna** [comment]
Assigned points - 8

**Comment by sly-yush** [comment]
Definition of Done:

Campaign strategists polled indicate they were able to tailor my social media content better.
